name: Backend Tests

on:
  push:
    branches:
      - main
      - develop

  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build containers
        run: docker compose build

      - name: Create env file
        run: cp .env.example .env.local

    #   - name: Run all tests
    #     run: docker compose run --rm backend ./test.sh

      - name: Run unit tests
        run: docker compose run --rm backend pytest tests/unit -v

      - name: Run integration tests
        run: docker compose run --rm backend pytest tests/integration -v

      - name: Run coverage
        run: docker compose run --rm backend pytest --cov